# Generated by Django 5.2.2 on 2025-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='alergenos',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('AL', 'Alimento'), ('BE', 'Bebida'), ('LP', 'Limpeza'), ('MA', 'Material'), ('EQ', 'Equipamento'), ('VE', 'Veículo'), ('MB', 'Mobiliário'), ('OU', 'Outros')], max_length=2, verbose_name='Tipo'),
        ),
    ]
