# Generated by Django 5.2.2 on 2025-06-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
