# Generated by Django 5.2.2 on 2025-06-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_fornecedor_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('AL', 'Alimento'), ('BE', 'Bebida'), ('LP', 'Limpeza'), ('MA', 'Material'), ('EQ', 'Equipamento'), ('VE', 'Veículo'), ('MB', 'Mobiliário'), ('DE', 'Decoração'), ('UT', 'Utensílios'), ('UN', 'Uniforme'), ('SE', 'Segurança'), ('EN', 'Energia'), ('FL', 'Floral'), ('TE', 'Têxtil'), ('OU', 'Outros')], max_length=2, verbose_name='Tipo'),
        ),
    ]
