# Generated by Django 5.2.2 on 2025-06-08 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápios',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='tipos_evento/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('data_evento', models.DateTimeField()),
                ('endereco', models.TextField()),
                ('numero_convidados', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('CO', 'Confirmado'), ('AN', 'Cancelado'), ('RE', 'Realizado'), ('PA', 'Pago')], default='PE', max_length=2)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cardapio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.cardapio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('tipo_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Consumo do Evento',
                'verbose_name_plural': 'Consumos dos Eventos',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Alocação de Funcionário',
                'verbose_name_plural': 'Alocações de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='ItemCompraCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('KG', 'Quilograma'), ('GR', 'Grama'), ('LT', 'Litro'), ('MT', 'Metro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('DZ', 'Dúzia'), ('SC', 'Saco'), ('FD', 'Fardo'), ('RL', 'Rolo'), ('PCT', 'Pacote'), ('TON', 'Tonelada')], default='UN', max_length=3)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='eventos.cardapio')),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
            },
        ),
        migrations.AddField(
            model_name='cardapio',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.tipoevento'),
        ),
    ]
