# Generated by Django 5.2.2 on 2025-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_tipoevento_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumoevento',
            options={'verbose_name': 'Consumo do Evento - Estoque', 'verbose_name_plural': 'Consumos dos Eventos - Estoque'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_evento',
        ),
        migrations.RemoveField(
            model_name='itemcompracardapio',
            name='descricao',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='numero_convidados',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
