# Generated by Django 5.2.2 on 2025-06-12 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_consumoevento_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='endereco',
        ),
        migrations.CreateModel(
            name='EnderecoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logadouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(blank=True, max_length=100, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Endereços do Evento',
                'verbose_name_plural': 'Endereços dos Eventos',
            },
        ),
    ]
