# Generated by Django 5.2.2 on 2025-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_evento_endereco_enderecoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
