# Generated by Django 5.2.2 on 2025-06-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alocacaofuncionario_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
