# Generated by Django 5.2.2 on 2025-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_alter_funcionario_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('PE', 'Permanente'), ('PS', 'Prestador de Serviço')], default='PS', max_length=2),
        ),
    ]
