# Generated by Django 5.2.2 on 2025-06-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_email_alter_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Documento',
        ),
    ]
