# Generated by Django 5.2.2 on 2025-06-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_documentos_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatocliente',
            options={'verbose_name': 'Contatos do Cliente', 'verbose_name_plural': 'Contatos dos Clientes'},
        ),
    ]
