# Generated by Django 5.2.2 on 2025-06-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_consumoevento_options_alter_evento_options_and_more'),
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriafinanceira',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='lancamentofinanceiro',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='lancamentofinanceiro',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='lancamentofinanceiro',
            name='evento',
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pelo Contrato')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos/', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('CO', 'Confirmado'), ('AN', 'Cancelado'), ('RE', 'Realizado'), ('PA', 'Pago')], default='PE', max_length=2)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.evento')),
            ],
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.contrato'),
        ),
    ]
