# Generated by Django 5.2.2 on 2025-06-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromovimento',
            name='data_saida',
            field=models.DateTimeField(),
        ),
    ]
